name: Spellcheck app
on: [pull_request]

jobs:
  app-spellcheck:
    strategy:
      matrix:
        node-version: [16.x]
        platform: [ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run cspell spellchecking
        run: yarn check-spelling
