name: 'Lint & test pull request'
on: [pull_request]

jobs:
  build-and-test:
    strategy:
    matrix:
      node-version: [16.x]
      platform: [ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint
        working-directory: ./app
        run: yarn lint:export
        continue-on-error: true
      - name: Annotate linting result
        if: ${{ !github.actor == 'dependabot[bot]' }}
        uses: ataylorme/eslint-annotate-action@1.2.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          report-json: 'app/eslint_report.json'
